name: Build and Deploy
on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: "managercalculator" # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "./src/api" # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: "3.9.7" # set this to the python version to use
  STARTUP_COMMAND: "" # set this to the startup command required to start the gunicorn server. default it is empty

jobs:
  Build:
    name: Build and Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependancies
        run: |
          pip install -U mypy
          pip install -U flake8
          pip install -U autopep8
          pip install -U uptime
          pip install -U Flask

      - name: Unittest
        run: python3 -m unittest discover

      - name: Building web app
        uses: azure/appservice-build@v2
        with:
          source-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          output-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Creating artifact directories
        run: |
          mkdir buildartifacts
          mkdir deploymenttemplates

      - name: Archive build artifact
        run: |
          zip -qq -r ./buildartifacts/Application.zip ./src

      - name: Uploading application to artifact store
        continue-on-error: false
        uses: actions/upload-artifact@v2
        with:
          name: buildartifacts
          path: buildartifacts

      - name: Uploading Arm Template to artifact store
        continue-on-error: false
        uses: actions/upload-artifact@v2
        with:
          name: deploymenttemplates
          path: deploymenttemplates

  Deploy:
    name: Deploy to azure web app
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Downloading build artifact
        uses: actions/download-artifact@v2
        with:
          name: buildartifacts
          path: buildartifacts

      - name: Unzipping build artifacts
        run: |
          unzip -qq ./buildartifacts/Application.zip -d .

      - name: Azure Login
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Deploy web app"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          startup-command: ${{ env.STARTUP_COMMAND }}

      - name: logout
        run: |
          az logout
